spring:
  datasource:
    url: ${IM_SERVER_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/service_im_server_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${IM_SERVER_DATASOURCE_USERNAME:root}
    password: ${IM_SERVER_DATASOURCE_PASSWORD}
