spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
  cloud:
    refresh:
      enabled: false
    openfeign:
      lazy-attributes-resolution: false
      client:
        refresh-enabled: false
  threads:
    virtual:
      enabled: false

springdoc:
  api-docs:
    enabled: ${IM_NATIVE_SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${IM_NATIVE_SWAGGER_UI_ENABLED:false}
