server:
  port: 8090

spring:
  application:
    name: im-log-service
  config:
    import:
      - optional:nacos:application-kafka.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yml
        import-check:
          enabled: false
        shared-configs:
          - data-id: application-kafka.yml
            refresh: true

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    consumer:
      group-id: log-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

im:
  jwt:
    enabled: false # log service does not need standard jwt filter if it's internal or admin-only
