spring:
  datasource:
    url: ${MESSAGE_SERVICE_DATASOURCE_URL:jdbc:mysql://im-mysql:3306/service_message_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&useLocalSessionState=true}
    username: ${MESSAGE_SERVICE_DATASOURCE_USERNAME:root}
    password: ${MESSAGE_SERVICE_DATASOURCE_PASSWORD}
