server:
  port: 8091

spring:
  application:
    name: im-admin-service
  config:
    import:
      - optional:nacos:application-kafka.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:im-nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:im-nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yml
        import-check:
          enabled: false

im:
  jwt:
    enabled: true
