im:
  registry-monitor:
    nacos:
      base-url: http://127.0.0.1:8848/nacos
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-configs:
          - data-id: application-mysql.yml
            refresh: true
          - data-id: application-redis.yml
            refresh: true
          - data-id: application-kafka.yml
            refresh: true
