export const USER_ENDPOINTS = {
  LOGIN: '/user/login',
  REGISTER: '/user/register',
  PROFILE: '/user/profile',
  SEARCH: '/user/search',
  LOGOUT: '/user/logout',
  HEARTBEAT: '/user/heartbeat',
  ONLINE_STATUS: '/user/online-status',
  PASSWORD: '/user/password',
  PHONE_CODE: '/user/phone/code',
  PHONE_BIND: '/user/phone/bind',
  EMAIL_CODE: '/user/email/code',
  EMAIL_BIND: '/user/email/bind',
  ACCOUNT: '/user/account',
  SETTINGS: '/user/settings',
  SETTINGS_TYPE: '/user/settings/:type',
} as const;
