spring:
  datasource:
    url: ${GROUP_SERVICE_DATASOURCE_URL:jdbc:mysql://im-mysql:3306/service_group_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${GROUP_SERVICE_DATASOURCE_USERNAME:root}
    password: ${GROUP_SERVICE_DATASOURCE_PASSWORD}
